"""Compatibility re-exports for validation rule helpers.

Prefer importing from the focused sibling modules: ``raw_helpers``,
``hierarchy_walkers``, ``hierarchy_projection``, and ``sidecar_projection``.
"""

from __future__ import annotations

from chaos_librarian.validation.rules.hierarchy_projection import (
    HierarchyMutation,
    HierarchyProjection,
    SwapValidity,
    build_hierarchy_projection,
    is_hierarchy_action,
)
from chaos_librarian.validation.rules.hierarchy_walkers import (
    NS_ALBUM_ID,
    NS_ARTIST_ID,
    NS_ASSET_ID,
    NS_BUNDLE_ID,
    NS_DISC_ID,
    NS_EPISODE_ID,
    NS_MOVIE_ID,
    NS_PODCAST_EPISODE_ID,
    NS_PODCAST_ID,
    NS_SEASON_ID,
    NS_SERIES_ID,
    NS_TRACK_ID,
    NS_VARIANT_ID,
    DeclaredSidecar,
    RawAssetContext,
    entity_ids_by_kind,
    iter_asset_contexts,
    iter_asset_ids,
    iter_assets_with_loc,
    iter_declared_roots,
    iter_declared_sidecars,
    iter_entity_ids,
    iter_global_namespaces,
    primary_root_path,
    renderable_context_for,
    rendered_asset_paths,
)
from chaos_librarian.validation.rules.raw_helpers import (
    Reporter,
    Rule,
    _as_list,
    _as_mapping,
    _iter_timeline_events,
    _list_at_path,
    _Loc,
    _RawMapping,
    first_or_duplicate,
    index_start_commit_events,
    report_unpaired_start,
    try_parse_duration,
)
from chaos_librarian.validation.rules.sidecar_projection import (
    SidecarProjection,
    SidecarProjectionRow,
    drop_subtitle_rows_for_language,
    project_sidecars_for_hierarchy_mutation,
    seed_sidecar_projection,
)

__all__ = [
    "NS_ALBUM_ID",
    "NS_ARTIST_ID",
    "NS_ASSET_ID",
    "NS_BUNDLE_ID",
    "NS_DISC_ID",
    "NS_EPISODE_ID",
    "NS_MOVIE_ID",
    "NS_PODCAST_EPISODE_ID",
    "NS_PODCAST_ID",
    "NS_SEASON_ID",
    "NS_SERIES_ID",
    "NS_TRACK_ID",
    "NS_VARIANT_ID",
    "DeclaredSidecar",
    "HierarchyMutation",
    "HierarchyProjection",
    "RawAssetContext",
    "Reporter",
    "Rule",
    "SidecarProjection",
    "SidecarProjectionRow",
    "SwapValidity",
    "_Loc",
    "_RawMapping",
    "_as_list",
    "_as_mapping",
    "_iter_timeline_events",
    "_list_at_path",
    "build_hierarchy_projection",
    "drop_subtitle_rows_for_language",
    "entity_ids_by_kind",
    "first_or_duplicate",
    "index_start_commit_events",
    "is_hierarchy_action",
    "iter_asset_contexts",
    "iter_asset_ids",
    "iter_assets_with_loc",
    "iter_declared_roots",
    "iter_declared_sidecars",
    "iter_entity_ids",
    "iter_global_namespaces",
    "primary_root_path",
    "project_sidecars_for_hierarchy_mutation",
    "renderable_context_for",
    "rendered_asset_paths",
    "report_unpaired_start",
    "seed_sidecar_projection",
    "try_parse_duration",
]
