"""Facade for materializer content-source families."""

from __future__ import annotations

from chaos_librarian.materializer.content.media_sources import (
    AUDIO_RECIPES,
    FPS_DEFAULT,
    PROVIDER_NAME,
    RESOLUTION_PIXELS,
    VIDEO_RECIPES,
    AudioRecipe,
    AudioSourceRequest,
    SourceResolution,
    VideoRecipe,
    VideoSourceRequest,
    resolve_audio_input,
    resolve_audio_source,
    resolve_video_input,
    resolve_video_source,
)
from chaos_librarian.materializer.content.metadata_sources import (
    CHAPTER_PROVIDER_NAME,
    COVER_ART_PROVIDER_NAME,
    COVER_ART_SIZE,
    ChapterSourceRequest,
    ChapterSourceResolution,
    ChapterSpec,
    CoverArtSourceRequest,
    CoverArtSourceResolution,
    resolve_chapter_source,
    resolve_cover_art_source,
)
from chaos_librarian.materializer.content.muxing_sources import (
    MUXING_PROVIDER_NAME,
    MuxingSourceRequest,
    MuxingSourceResolution,
    resolve_muxing_source,
)
from chaos_librarian.materializer.content.source_capabilities import (
    AUDIO_NOISE_CAPABILITY_SOURCES,
    AUDIO_SAMPLE_FORMAT_CAPABILITY_SOURCES,
    AUDIO_SAMPLE_RATE_CAPABILITY_SOURCES,
    COLOR_RANGE_CAPABILITY_SOURCES,
    COLOR_SPACE_CAPABILITY_SOURCES,
    HDR_CAPABILITY_SOURCES,
    INTERLACED_CAPABILITY_SOURCES,
    RESOLUTION_SEQUENCE_CAPABILITY_SOURCES,
    VFR_CAPABILITY_SOURCES,
    collect_content_source_capabilities,
)

__all__ = [
    "AUDIO_NOISE_CAPABILITY_SOURCES",
    "AUDIO_RECIPES",
    "AUDIO_SAMPLE_FORMAT_CAPABILITY_SOURCES",
    "AUDIO_SAMPLE_RATE_CAPABILITY_SOURCES",
    "CHAPTER_PROVIDER_NAME",
    "COLOR_RANGE_CAPABILITY_SOURCES",
    "COLOR_SPACE_CAPABILITY_SOURCES",
    "COVER_ART_PROVIDER_NAME",
    "COVER_ART_SIZE",
    "FPS_DEFAULT",
    "HDR_CAPABILITY_SOURCES",
    "INTERLACED_CAPABILITY_SOURCES",
    "MUXING_PROVIDER_NAME",
    "PROVIDER_NAME",
    "RESOLUTION_PIXELS",
    "RESOLUTION_SEQUENCE_CAPABILITY_SOURCES",
    "VFR_CAPABILITY_SOURCES",
    "VIDEO_RECIPES",
    "AudioRecipe",
    "AudioSourceRequest",
    "ChapterSourceRequest",
    "ChapterSourceResolution",
    "ChapterSpec",
    "CoverArtSourceRequest",
    "CoverArtSourceResolution",
    "MuxingSourceRequest",
    "MuxingSourceResolution",
    "SourceResolution",
    "VideoRecipe",
    "VideoSourceRequest",
    "collect_content_source_capabilities",
    "resolve_audio_input",
    "resolve_audio_source",
    "resolve_chapter_source",
    "resolve_cover_art_source",
    "resolve_muxing_source",
    "resolve_video_input",
    "resolve_video_source",
]
